export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT'
export const INCREMENT_BY_FIVE = 'INCREMENT_BY_FIVE'
export const DECREMENT_BY_FIVE = 'DECREMENT_BY_FIVE'
export const STORE_RESULT = 'STORE_RESULT'
export const DELETE_RESULT = 'DELETE_RESULT'


